// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Node struct {
	ID        int32
	Name      string
	RouteID   int32
	Sequence  int32
	Location  interface{}
	UpdatedAt sql.NullTime
}

type Route struct {
	ID       int32
	Name     string
	Geom     interface{}
	Distance float32
	Duration float32
}

type User struct {
	ID            int32
	Name          string
	Institution   string
	Address       string
	ApproxAddress bool
	Location      interface{}
	UpdatedAt     sql.NullTime
}
