// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: routes.sql

package db

import (
	"context"
)

const insertRoute = `-- name: InsertRoute :one
INSERT INTO routes (name, geom, distance, duration) VALUES (
    $1,
    ST_SetSRID(ST_LineFromEncodedPolyline($2::text, 5), 4326),
    $3,
    $4
)
RETURNING id
`

type InsertRouteParams struct {
	Name     string
	Polyline string
	Distance float32
	Duration float32
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertRoute,
		arg.Name,
		arg.Polyline,
		arg.Distance,
		arg.Duration,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
